AWSTemplateFormatVersion: 2010-09-09
Description: Vertification Containers Deploy

Resources:
  DeployPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            PolicyName: VerificationPipelinePolicy
        Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - codebuild:*
              - codedeploy:*
              - s3:*
              - cloudformation:*
              - iam:PassRole
              - sns:Publish
              - ecr:*
              - ecs:*
              - elasticloadbalancing:*
              - cloudwatch:*
              Effect: Allow
              Resource: '*'
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
        Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - logs:CreateLogStream
              - logs:PutLogEvents
              - iam:PassRole
              Effect: Allow
              Resource: '*'
            Version: "2012-10-17"
  FargateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref FargateCidrBlock
  FargateCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    CidrBlock: 10.111.0.0/16
    VpcId: !Ref FargateVPC
  FargateGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: FargateGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref FargateGateway
      VpcId: !Ref FargateVPC
  FargateRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref FargateVPC
      Tags:
      - Key: Name
        Value: FargateRouteTable
  FargateRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FargateGateway
      RouteTableId: !Ref FargateRouteTable
  FargateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.111.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: FargateSubnetAZ1
      VpcId: !Ref FargateVPC
  FargateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.111.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: FargateSubnetAZ2
      VpcId: !Ref FargateVPC
  FargateALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: FargateALBSecurityGroup
      GroupDescription: For ALB SG
      VpcId: !Ref FargateVPC
  FargateALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: FargateALBTargetGroup
    LoadBalancerArn:
      Ref: FargateALB
    Port: 80
    Protocol: HTTP
  FargateALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: FargateALB
      Scheme: internet-facing
      SecurityGroups:
        Ref: FargateALBSecurityGroup
      SubnetMappings:
      Subnets:
        Ref: FargateSubnetAZ1
        Ref: FargateSubnetAZ2
      Type: application
  FargateALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FargateTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId:
        Ref: FargateVPC
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
  FargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: VerificationCluster
  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: VerificationCluster
      DisiredCount: 2
      LaunchType: FARGATE
      LoadBalanders: !Ref FargateALB
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
  CodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: CodeDeploy
      ComputePlatform: ECS
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore: !Ref ArtifactStoreBucket
      Name: Vertification Containers Deploy
      RoleArn:
        - !Ref DeployPipelineRole
      Stages:
        Actions:
        - ActionTypeID:
            Category: Source
            Owner: AWS
            Provider: ECR
            Version: 1
          Configuration:
            key: value
          Name: ContainerImagefromECR
          OutputArtifacts:
            - ECRArtifact
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 1
        - ActionTypeID:
            Category: Source
            Owner: AWS
            Provider: S3
            Version: 1
          Configuration:
            key: value
          Name: BuildSourcefromS3
          OutputArtifacts:
            - SourceArtifact
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 1
        - ActionTypeID:
            Category: Deploy
            Owner: AWS
            Provider: ECS
            Version: 1
          Configuration:
            key: value
          InputArtifacts:
            - ECRArtifact
          Name: DeoplytoFargate
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 2