AWSTemplateFormatVersion: 2010-09-09
Description: Vertification Containers Deploy

Resources:
  DeployPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            PolicyName: VerificationPipelinePolicy
        Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - codebuild:*
              - codedeploy:*
              - s3:*
              - cloudformation:*
              - iam:PassRole
              - sns:Publish
              - ecr:*
              - ecs:*
              - elasticloadbalancing:*
              - cloudwatch:*
              Effect: Allow
              Resource: '*'
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
        Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - logs:CreateLogStream
              - logs:PutLogEvents
              - iam:PassRole
              Effect: Allow
              Resource: '*'
            Version: "2012-10-17"
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
  CodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: CodeDeploy
      ComputePlatform: ECS
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore: !Ref ArtifactStoreBucket
      Name: Vertification Containers Deploy
      RoleArn:
        - !Ref DeployPipelineRole
      Stages:
        Actions:
        - ActionTypeID:
            Category: Source
            Owner: AWS
            Provider: ECR
            Version: 1
          Configuration:
            key: value
          Name: ContainerImagefromECR
          OutputArtifacts:
            - ECRArtifact
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 1
        - ActionTypeID:
            Category: Source
            Owner: AWS
            Provider: S3
            Version: 1
          Configuration:
            key: value
          Name: BuildSourcefromS3
          OutputArtifacts:
            - SourceArtifact
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 1
        - ActionTypeID:
            Category: Deploy
            Owner: AWS
            Provider: ECS
            Version: 1
          Configuration:
            key: value
          InputArtifacts:
            - ECRArtifact
          Name: DeoplytoFargate
          Region: ap-northeast-1
          RoleArn: !Ref DeployPipelineRole
          RunOrder: 2